
title: Quick OSINT
description: Проверка персональных данных на утечки
baseurl: ""
url: ""

theme: minima

plugins:
  - jekyll-seo-tag

jekyll-seo-tag:
  hide_generator: true

button_url: "ВАШ_URL_ЗДЕСЬ"
